### PR TITLE
When player is standing on shadow or vice versa, take the block the b…

### LINKED ISSUE #16: Yet another collision bug
Try this level in the game:

~~~
size=800,600
tile(MovingBlock,400,350,50,50){
	MovingPosCount=4
	activated=1
	id=2
	loop=1
	t0=16
	t1=16
	t2=16
	t3=16
	x0=0
	x1=-50
	x2=-50
	x3=0
	y0=50
	y1=50
	y2=0
	y3=0
}
tile(PlayerStart,400,300,50,50)
tile(ShadowStart,400,250,50,50)
~~~

Then you will notice this bug:

bug2

I have checked that since commit 86423d7 this bug exists. I haven't checked for V0.4 and V0.4.1 versions.

### PR DESCRIPTION
**Pull request by edwardlii**
…ottom one is standing on into account during collision

Fixes #16

### CODE REVIEW

**Comment by acmepjz** [comment]
Thanks 😄

**Comment by acmepjz** [comment]
I have to say that the assertion `assert(other->objCurrentStand != NULL)` actually CAN happen, e.g. when player is holding shadow and the player is going to jump. Can you check if this can happen in your commit <https://github.com/edwardlii/meandmyshadow/commit/aa202e96be9d584259e72f215389691ef07cb313> ?

**Comment by edwardlii** [comment]
> Can you check if this can happen in your commit edwardlii@aa202e9 ?
Seems that it's also the case in my branch, though I'm fairly sure it wasn't at one point. Disabling the assertion for now is okay. Though I do think the situation itself a bit weird. We have the logic that the player (or shadow) can't hold the other when in the air themselves, handled in `otherCheck`, but when jumping (during `collision`) we mark the player as `inAir`, but is still holding the other.

For now, let's simply disable the assertion, as the code works just fine without it, but perhaps address this for V0.6 (along with the rest of the collision/movement)?

**Comment by acmepjz** [comment]
OK. I have already commented out the assertion.

**Pull request merged**
