### PR TITLE
SDL2 port

### PR DESCRIPTION
**Pull request by oyvindln**
So i fixed a few more issues, and attempted to merge in the upstream changes.

Joystick support is still missing though, and haven't checked that the latest commit compiles on windows yet.

### CODE REVIEW

**Comment by acmepjz** [comment]
Hi,

I have tested your code a little bit, and have the following remarks:

1. Unfortunately, VS2013 doesn't like your code; can you fix the following places to make it compile under VS2013? (Of course I can also fix these after merging your pull request)

* in Addons.h, add `#include <array>`
* replace all `snprintf` by `SDL_snprintf` except for two places in FileManager.cpp
* in GUIObjects.cpp, change the following two lines:
~~~c++
 	//Get the absolute x and y location.
 	x+=left;
 	y+=top;
 	//Create a clip rectangle.
-    SDL_Rect r{clip};
+    SDL_Rect r=clip;
 	//The width and height are capped by the GUIImage itself.
     if(r.w>width || r.w==0) {
 		r.w=width;
     }
     if(r.h>height || r.h==0) {
 		r.h=height;
     }
-    const SDL_Rect dstRect{x,y,r.w,r.h};
+    const SDL_Rect dstRect={x,y,r.w,r.h};
     SDL_RenderCopy(&renderer, image.get(), &r, &dstRect);
 }
~~~
I don't know why VS2013 doesn't like this code, though.

2. Can you confirm the following bugs?

* [ ] fade out is too fast compared to fade in
* [ ] level select screen tooltip bug
* [ ] Up scroll button not working properly. (You mentioned at the forum, but I can't figure out where is not working properly.)
* [ ] credit screen text box horizontal scroll bug

3. Do you build against lua 5.3? I have lua 5.2 only. If yes, then it means that the code also runs under lua5.3.

**Comment by oyvindln** [comment]
1.
I'll fix these. (Can't find the exact issue, but it seems VS2013 does lack a small number of C++11 features, both ways of initializing should be the same in practice though.)
2.
Fade out - yeah we'll have to tweak that.
Level select screen tooltip - not sure what you are referring too, do you have an example?
Up scroll - should be fixed, but let me know if there are places it isn't
credit screen - Yep, didn't catch that one before.
The achievements list box is also not showing the last item when it's partially obscured.

3. Yep, I'm using lua 5.3

**Comment by acmepjz** [comment]
The level name tooltip doesn't get updated when the level pack changed, as in the demonstration:

output

**Comment by acmepjz** [comment]
I plan to merge the pull request first, then fix the remaining minor bugs by myself. What's your opinion? @oyvindln

**Comment by oyvindln** [comment]
Yeah feel free to merge.

**Pull request merged**
