### PR TITLE
Russian & Ukrainian translations

### PR DESCRIPTION
**Pull request by eugeneloza**
Finally I've done the second stage of proof-reading for Russian, merged mine and @mesnevi's translations and solved the merge conflict. It'd be really nice, if @mesnevi could check the result before the release. Unfortunately the translation wasn't play-tested yet.

Ukrainian translation only passed the first stage of proof-reading and wasn't play-tested either. The text must be readable, but I hope I'll be able do finish the second stage of proof-reading at weekends.

I can playtest the translations, however, I need Win/Linux binaries with Russian/Ukrainian updated to the "last version". I'll hardly be able to compile them myself.

### CODE REVIEW

**Comment by acmepjz** [comment]
Hi eugeneloza,

Thank you for the translations! 😄 As for the Win/Linux binaries, you can just download the RC2 on Sourceforge, or better, download the latest nightly build from bintray <https://bintray.com/acmepjz/meandmyshadow/meandmyshadow/nightly-build#files> (which fixes a few bugs), then overwrite its ru.po, etc. by your newer one.

If you want the binary which contains your translations, I can merge this pull request immediately and the CI will do the build processes. However, in this way you need to open a new pull request if you made further modification to translations (before doing that you should make sure your fork is up-to-date since probably the Weblate will modify the comments in your translation files 😑).

**Comment by eugeneloza** [comment]
No, I just need them to be playable :D If I can simply place `ru.po` and `uk.po` and they will work automatically, then there is nothing more :)

**Comment by acmepjz** [comment]
Hello,

I decide to merge this now since I'll release the V0.5 tomorrow. If you made further modification to translations please open a new pull request. Thanks 😄

**Comment by eugeneloza** [comment]
Sure. I hope I'll be able to playtest Russian till tomorrow.

**Pull request merged**
