### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by mesnevi**
This is an update for 'translations' component of Me and My Shadow.
PO file was generated by Weblate.

Signed-off-by: Lesya Novaselskaya <shams@airpost.net>

### CODE REVIEW

**Comment by acmepjz** [comment]
Hi,

Thanks for your work! However, there are already people working on Russian translation (as well as Ukrainian translation), see <https://github.com/eugeneloza/meandmyshadow>. Maybe you can discuss with him first?

**Comment by mesnevi** [comment]
@acmepjz , I've updated strings on Weblate, but then I've come across #25 and got the idea that you would prefer pull requests with PO files included. Sure, proofreading is the thing I miss so much on other projects.

@eugeneloza , could you please review this pull request?

**Comment by eugeneloza** [comment]
@mesnevi hi!

Oh, I was afraid of something like that could happen :) I've finished Russian translation a few days ago, but I skimmed through this pull request and I really like some lines much better, than mine.

@acmepjz I saw you announced expected release date on 1 October? I'm very unlikely to finish third part of proof-reading by that point. So, I guess by the 1st October I'll be only able to merge mine and @mesnevi pull requests and (hopefully) do the second part of proof-reading. I guess the translation quality without the third sage will be enough to let the translation on its current state in release, but it really may be better.

On the other hand, "a fresh view" might do miracles :) Right now I'm deep in preparing for my lectures on Tuesday and Wednesday, so I'll hardly be able to look into the issue more careful before the 27th September. Maybe, together we can do it faster together with @mesnevi?

That said, I might suggest three ways we might take.

1. Merge @mesnevi translation into the Master, and as soon I'm back in shape after lectures, I'll fix the merge conflict that would obviously occur (yeah, I hate fixing merge conflicts :D). This path seems the best to me (because it's safe, while demands much more work and slows down the progress).

2. I may update my translation according to @mesnevi's fixes and submit it clean. I already see there're a lot of things, that are better than what I did. However, this will force to wait until I'm able to commit it (I guess postponing Release is a bad idea). And it would also "loose the commit authorship" of @mesnevi's lines, while I'll most certainly specify it in commit's header, technically speaking that's not good.

3. I'd be honored, if @mesnevi could have a fresh look at my translation and give fixes as commits - that will really increase both **speed** and **quality** of the translation. However, that'll require a lot of work on @mesnevi's side as the translations can't be "simply merged", weblate did change a lot in the translation file and fixing merge conflicts that large is not a trivial task.

**Comment by acmepjz** [comment]
> I've updated strings on Weblate, but then I've come across #25 and got the idea that you would prefer pull requests with PO files included.

No, currently I think it's better to translate on Weblate. It's also OK for pull requests.
However, I think it's bad to use both methods simultaneously, it certainly will introduce huge merge conflicts. BTW, I want to make sure then currently there are nobody translating the game into Russian on Weblate 😅.

> I saw you announced expected release date on 1 October? I'm very unlikely to finish third part of proof-reading by that point. 

Don't worry, we can discuss if the release date will be delayed. Do you have a rough estimate on the time of third part of proof-reading?

**Comment by acmepjz** [comment]
Oops, I clicked something on Weblate and the translation changes are push automatically onto the master branch ☹. @eugeneloza I think you have to resolve conflicts manually later, sorry.

**Comment by eugeneloza** [comment]
Well, then we're already going for path 1, but the hard way :D

~~You can resolve the conflict "relatively easily" the "last" po file version by simply replacing the file in local GIT and pushing them to Master. That'd gonna create 2 "pointless" commits that cancel each other, but will revert to the state "where it all started". You may get the last po file version from commit history~~ (on the second thought this won't help now)

Hmm... I've got another idea, @mesnevi maybe you could push the strings (copy-paste) in the current pull request through Weblate so that they'll be compatible to your Weblate commits that were just merged? This won't solve the merge conflict, but then this pull request may be closed and different changes canceled out by just physically copying the `ru.po` file to the `mesnevi:ru_locale_update`.

P.S. Yeah, that's why I avoided using `PoEdit` for editing, only used it for checking, as it had its own idea on how to save the file. Even different versions would spawn ambiguous changes in po files.

> I clicked something

Yeah, that's what I hate about GIT. One click and a merge conflict or a collapsed branch :) Happens to me too. Even in a project only one contributor is working at.

> Do you have a rough estimate on the time of third part of proof-reading?

Theoretically I might manage it by 1 October. Thou this is utopic :) More realistic estimate would be 10-11 October - after I'm done with all my lectures and, hopefully, OpenJam. And that'd much better accommodate for playtesting the translation too. I may give a better estimate at Wednesday when I know how I survived the first lectures :D and how much more preparation work is needed.

However, as I've said before, the translation as-is is already _readable_. It may then be improved after the release if something may be said "better". The idea is the following:

Part 1 - (reading in electronic) fix typos and terminology.
Part 2 - (reading in print) fix style.
Playtesting - (in electronic) to be sure, that all the phrases are correct in context and don't get too large to overlap other objects on screen.
Part 3 - (reading in print) in ideal world would result in zero corrections, but usually there are things to improve.

**Comment by mesnevi** [comment]
@eugeneloza this file (ru.po) which I included in my commit, was actually generated by Weblate after I've done some translating there, so the strings are already in their system. The only thing I've changed before committing was filename itself and several lines in file header, which were commented out and contained some info about translator and copyrights). I'm ready to help in any way you consider proper, so let me check Weblate and see what's going on. 

Did I get you right, you fix merge conflicts by pushing files to Weblate directly? Or do you get .PO from there and all the merging fun is going on here? I'll be glad to review your translaton as well, I believe that proof-reading and reviewing step improves product quality and season yourself in the process. 

@acmepjz Sure thing, I prefer Weblate, too. Sorry for the mess, will do my best to fix things up.

**Comment by eugeneloza** [comment]
> The only thing I've changed before committing...

Yes, that's the problem with "Complex" editing tools. They seem to spawn a lot of additional changes, there is no need to (or might even be harmful).
E.g. check the "changed files" in this pull request. It has not only strings changed, but also reference lines of the code, e.g. here https://github.com/acmepjz/meandmyshadow/pull/27/files#diff-0b77a8735df04d746cd30968ec5dab7dL1561  - they seem like comments and should be Ok thou. But really, why would the same Weblate change those differently at different edits? Well, that's rhetoric :)

> Did I get you right, you fix merge conflicts by pushing files to Weblate directly?

Not actually. Fixing merge conflicts is a quiet delicate procedure. In short now we're merging two edits. It's Ok unless both edits concern a single line and the GIT system can't tell which is "better" (it's not an AI). It marks those as conflict, and each such lines should be fixed manually by either leaving the first correction, or the second, or fusing them.

However, in our current situation, we have now **two** merge conflicts (or rather **three** - one between `Master` and `mesnevi:ru_locale_update`, one between `Master` and `eugeneloza:master` and one between `mesnevi:ru_locale_update` and `eugeneloza:master` - however, once two of those are fixed, the third one is fixed automatically). It's not disastrous, just requires some work. However, hosted Weblate shouldn't have problems with merging something into Master, I guess it just overwrites it. This way we might try to ignore the 1 of 2 merge conflicts and submit everything through Weblate instead of pull request.

However, after looking through the pull request again I see that about 200 lines were changed, that's a lot for simple copy-pasting, so going for manual merge conflict fixing might be easier and faster.

> I believe that proof-reading and reviewing step improves product quality and season yourself in the process.

I couldn't agree more! :)

**Comment by acmepjz** [comment]
OK, then this means that @mesnevi  your work is already merged into master through Hosted Weblate and we are safe to close this pull request. Is it correct?

@eugeneloza  you can submit a pull request if you find the current translation is usable (but not final version) at some point. You can always submit another pull request for final version later. I think the release date may be a bit delayed due to some additional bug reports and feature requests.

**Comment by eugeneloza** [comment]
> Is it correct?

No. This pull request contains about 200 more lines translated than the one in the Master (pushed directly through hosted Weblate), that's almost 40% of the translation. See the diff: https://github.com/acmepjz/meandmyshadow/pull/27/files

> if you find the current translation is usable

Ok, let's then make it this way. Just ping me if the deadline would be extended (I also keep track of freegamedev topics) and I'll try my best to submit a pull before 1 October and will notify on the translation finalization state.

**Comment by acmepjz** [comment]
> No. This pull request contains about 200 more lines translated than the one in the Master (pushed directly through hosted Weblate), that's almost 40% of the translation.

I see. I'll merge this pull request by manually resolve conflicts then.

[EDIT] In fact the additional lines are mostly re-formatting of comments 😑

[EDIT2] And then Weblate is unhappy about the comment changes, and revert all of them back! (The translated strings themselves are OK, though.)

**Comment by eugeneloza** [comment]
Great! One problem less to worry about :)

**Comment by mesnevi** [comment]
@eugeneloza  @acmepjz is there anything I can help with?

**Pull request merged**
