### PR TITLE
Prefer custom SDL_ttf over system's SDL_ttf to access extra functions.

### PR DESCRIPTION
**Pull request by gunchleoc**
I kept hitting the system SDL_ttf library instead of the custom-made one, so I changed the load order in CMake.

Swapping out the file is a bit hacky anyway, but I don't want to do more refactoring right now.

### CODE REVIEW

**Comment by acmepjz** [comment]
I see the changes of the order of include directories you made. Maybe I think I should also change the file name of custom SDL_ttf to `SDL_ttf_hacked`? Then the compiler won't include wrong header files anymore. 😄

**Comment by gunchleoc** [comment]
Renaming the header file would certainly work. Call it `SDL_ttf_expanded`?

**Comment by acmepjz** [comment]
I think `SDL_ttf_fontfallback` fits best with it, since I added an extra function called `FontFallback`.

**Comment by gunchleoc** [comment]
OK, done.

**Comment by acmepjz** [comment]
Thanks!

**Pull request merged**
